models_params = {'lr': {'fit_intercept': False},
 'lasso': {'fit_intercept': True, 'alpha': 0.02},
 'ridge': {'fit_intercept': False, 'alpha': 9.98},
 'en': {'random_state': 42,
  'l1_ratio': 0.535,
  'fit_intercept': False,
  'alpha': 0.05},
 'lar': {'random_state': 42, 'fit_intercept': True, 'eps': 0.1},
 'llar': {'random_state': 42,
  'fit_intercept': False,
  'eps': 1e-05,
  'alpha': 0.01},
 'br': {'lambda_2': 1e-06,
  'lambda_1': 0.3,
  'fit_intercept': False,
  'compute_score': False,
  'alpha_2': 0.3,
  'alpha_1': 0.05},
 'ard': {'threshold_lambda': 55000,
  'lambda_2': 1e-06,
  'lambda_1': 0.3,
  'fit_intercept': False,
  'compute_score': False,
  'alpha_2': 0.3,
  'alpha_1': 0.0001},
 'par': {'random_state': 42,
  'shuffle': True,
  'loss': 'epsilon_insensitive',
  'fit_intercept': False,
  'epsilon': 0.6,
  'C': 0.005},
 'ransac': {'random_state': 42,
  'stop_probability': 0.02,
  'stop_n_inliers': 6,
  'min_samples': 0.75,
  'max_trials': 10,
  'max_skips': 18,
  'loss': 'absolute_error'},
 'tr': {'random_state': 42, 'fit_intercept': True},
 'huber': {'fit_intercept': False, 'epsilon': 1, 'alpha': 0.1},
 'kr': {'alpha': 0.9},
 'svm': {'shrinking': True, 'epsilon': 1.1, 'C': 1.601},
 'knn': {'weights': 'distance', 'n_neighbors': 11, 'metric': 'minkowski'},
 'dt': {'random_state': 42,
  'min_samples_split': 10,
  'min_samples_leaf': 2,
  'min_impurity_decrease': 0.0001,
  'max_features': 1.0,
  'max_depth': 5,
  'criterion': 'absolute_error'},
 'rf': {'random_state': 42,
  'n_estimators': 230,
  'min_samples_split': 9,
  'min_samples_leaf': 5,
  'min_impurity_decrease': 0.0001,
  'max_features': 1.0,
  'max_depth': 10,
  'criterion': 'squared_error',
  'bootstrap': True},
 'et': {'random_state': 42,
  'n_estimators': 230,
  'min_samples_split': 2,
  'min_samples_leaf': 3,
  'min_impurity_decrease': 0.0001,
  'max_features': 1.0,
  'max_depth': 10,
  'criterion': 'squared_error',
  'bootstrap': False},
 'ada': {'random_state': 42,
  'n_estimators': 230,
  'loss': 'square',
  'learning_rate': 0.15},
 'gbr': {'random_state': 42,
  'subsample': 0.35,
  'n_estimators': 140,
  'min_samples_split': 5,
  'min_samples_leaf': 5,
  'min_impurity_decrease': 0.002,
  'max_features': 1.0,
  'max_depth': 7,
  'learning_rate': 0.05},
 'mlp': {'random_state': 42,
  'learning_rate': 'invscaling',
  'hidden_layer_sizes': (100, 50),
  'alpha': 0.7,
  'activation': 'logistic'},
 'xgboost': {'random_state': 42,
  'subsample': 0.5,
  'scale_pos_weight': 22.1,
  'reg_lambda': 0.005,
  'reg_alpha': 1e-07,
  'n_estimators': 160,
  'min_child_weight': 2,
  'max_depth': 4,
  'learning_rate': 0.05,
  'colsample_bytree': 1},
 'lightgbm': {'random_state': 42,
  'verbose': -1,
  'reg_lambda': 0.005,
  'reg_alpha': 1,
  'num_leaves': 150,
  'n_estimators': 270,
  'min_split_gain': 0.5,
  'min_child_samples': 41,
  'learning_rate': 0.05,
  'feature_fraction': 1.0,
  'bagging_freq': 1,
  'bagging_fraction': 0.6},
 'catboost': {'random_state': 42,
  'verbose': 0,
  'random_strength': 0.4,
  'n_estimators': 250,
  'l2_leaf_reg': 8,
  'eta': 0.1,
  'depth': 7},
 'Bagging': {'random_state': 42,
  'max_samples': 0.6,
  'max_features': 0.6,
  'bootstrap_features': False,
  'bootstrap': False}}